package com.automation.api.utils;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

// Per-feature-file test data, generated by the AI alongside the .feature file itself (see
// framework/SKILL.md "Per-Feature Test Data"). Deliberately replaces TestDataGenerator for
// payload construction: values here are fixed and deduplicated (one "email" key reused across
// every scenario in the feature via "base", only the differing variant sits under "values"),
// not freshly randomized per call. TestDataGenerator itself is untouched -- ApiContext still
// uses it for unrelated "{{random.field}}" token resolution.
public class TestDataResolver {
    private static final Path TESTDATA_DIR = Paths.get("src/test/resources/testdata");
    private static final ObjectMapper JSON = new ObjectMapper();
    private static final Map<String, JsonNode> CACHE = new ConcurrentHashMap<>();

    private TestDataResolver() {
    }

    public static Map<String, Object> loadBase(String featureSlug, String model) {
        JsonNode base = modelNode(featureSlug, model).get("base");
        Map<String, Object> out = new LinkedHashMap<>();
        if (base != null && base.isObject()) {
            Iterator<Map.Entry<String, JsonNode>> fields = base.fields();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> field = fields.next();
                out.put(field.getKey(), JSON.convertValue(field.getValue(), Object.class));
            }
        }
        return out;
    }

    // Fails fast (never silently no-ops) on an unknown key -- an AI-generated feature file
    // referencing a variant that doesn't exist in the matching testdata file is a real bug in
    // generation, not something to paper over at runtime.
    public static void applyValue(Map<String, Object> payload, String featureSlug, String model, String key) {
        JsonNode values = modelNode(featureSlug, model).get("values");
        if (values == null || !values.has(key)) {
            throw new IllegalStateException(
                "Unknown test data key \"" + key + "\" for model \"" + model + "\" in "
                    + testDataPath(featureSlug) + " -- available keys: " + availableKeys(values, key));
        }
        String field = key.contains(":") ? key.substring(0, key.indexOf(':')) : key;
        JsonNode value = values.get(key);
        if (value.isTextual() && "$remove".equals(value.asText())) {
            payload.remove(field);
        } else {
            payload.put(field, JSON.convertValue(value, Object.class));
        }
    }

    private static String availableKeys(JsonNode values, String key) {
        if (values == null) {
            return "(no \"values\" block defined for this model)";
        }
        String prefix = key.contains(":") ? key.substring(0, key.indexOf(':') + 1) : "";
        StringBuilder sb = new StringBuilder();
        values.fieldNames().forEachRemaining(k -> {
            if (prefix.isEmpty() || k.startsWith(prefix)) {
                if (sb.length() > 0) {
                    sb.append(", ");
                }
                sb.append(k);
            }
        });
        return sb.length() > 0 ? sb.toString() : "(none for that field)";
    }

    private static JsonNode modelNode(String featureSlug, String model) {
        JsonNode root = load(featureSlug);
        JsonNode node = root.get(model);
        if (node == null) {
            throw new IllegalStateException(
                "No model \"" + model + "\" found in " + testDataPath(featureSlug)
                    + " -- confirm the generated testdata file defines this model key.");
        }
        return node;
    }

    private static JsonNode load(String featureSlug) {
        return CACHE.computeIfAbsent(featureSlug, slug -> {
            Path path = testDataPath(slug);
            if (!Files.exists(path)) {
                throw new IllegalStateException(
                    "No test data file found at " + path.toAbsolutePath()
                        + " -- every generated feature file must have a matching testdata/<slug>.json.");
            }
            try (InputStream input = Files.newInputStream(path)) {
                return JSON.readTree(input);
            } catch (Exception e) {
                throw new IllegalStateException("Failed to read " + path.toAbsolutePath(), e);
            }
        });
    }

    private static Path testDataPath(String featureSlug) {
        return TESTDATA_DIR.resolve(featureSlug + ".json");
    }
}
